### ISSUE TITLE
there is no documentation for GetInboxRequest

### ISSUE THREAD

**Issue by john-aura** [manybrain/mailinator-javascript-client#1]
your example to get an inbox looks like this, but i don't know what GetInboxRequest is

const response: IRestResponse<Inbox> = await mailinatorClient.request(
            new GetInboxRequest("yourDomainNameHere")
        );

**Comment by marianmelnychuk** [comment]
> your example to get an inbox looks like this, but i don't know what GetInboxRequest is
> 
> 
> 
> const response: IRestResponse<Inbox> = await mailinatorClient.request(
> 
>             new GetInboxRequest("yourDomainNameHere")
> 
>         );

The documentation here is not good at all for sure, I'll try to fix it soon. But I think its not a big deal, because IntelliSense should show you function variables and I hope it could be helpful. 

I can also attach GetInboxRequest object constructor

`constructor(private readonly domain: string,
                private readonly inbox?: string,
                private readonly skip?: number,
                private readonly limit?: number,
                private readonly sort?: Sort,
                private readonly decodeSubject?: boolean) {
    }`

Feel free to let me know if anything else is needed.
